# Generated by Django 5.2.4 on 2025-08-02 10:26

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="birthday",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(1900, 1, 1),
                        message="Birthday cannot be before 1900",
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2025, 8, 2),
                        message="Birthday cannot be in the future",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="appuser",
            index=models.Index(
                fields=["birthday"], name="core_appuse_birthda_1eeff6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerrelationship",
            index=models.Index(fields=["points"], name="core_custom_points_21cc73_idx"),
        ),
    ]
